[package]
name = "ds4ugly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs-core = "0.5.6"
vigem-client = { version = "0.1.4", features = ["unstable_ds4"] }
